#!/bin/bash

DATE_NOW=$(date -Ru | sed 's/\+0000/GMT/')
AZ_VERSION="2018-03-28"
AZ_BLOB_URL="https://eiot.blob.core.windows.net"
AZ_BLOB_CONTAINER="epd"
AZ_BLOB_TARGET="${AZ_BLOB_URL}/${AZ_BLOB_CONTAINER}/"
AZ_SAS_TOKEN="..."

curl -v -H "Content-Type: application/octet-stream" \
		-H "x-ms-date: ${DATE_NOW}" \
		-H "x-ms-version: ${AZ_VERSION}" \
		-H "x-ms-blob-type: BlockBlob" \
		"${AZ_BLOB_TARGET}${1}${AZ_SAS_TOKEN}"
